### ISSUE TITLE
No GPS on iBUS

### ISSUE THREAD

**Issue by wamboin23** [dgatf/msrc#119]
Unable to get GPS working with iBus.

Using NEO6M GPS and RP2040-Zero. Confirmed NEO6M working as expected using both ESP8266 and direct serial to PC.

Flysky transmitter finds GPS as sensor(s), but all zeros for all GPS related data.

Compiled with simulated sensors as test, and transmitter displays data as defined in SIM_SENSORS.

Have tried disabling all other sensors to ensure no conflicts.

Debug data from MSRC GUI as follows:

> USB. Debug enabled
> USB (115)
> Ibus (210) < 4 A2 59 FF 
> Ibus (132) > 6 A2 0 0 57 FF 
> Ibus (120) < 4 A3 58 FF 
> Ibus (120) > 8 A3 0 0 0 0 54 FF 
> Ibus (120) < 4 A4 57 FF 
> Ibus (120) > 8 A4 0 0 0 0 53 FF 
> Ibus (120) < 4 A5 56 FF 
> Ibus (120) > 8 A5 0 0 0 0 52 FF 
> Ibus (120) < 4 A6 55 FF 
> Ibus (120) > 6 A6 0 0 53 FF 
> Vspeed (224): 0.00
> Distance (224): 0.00
> Ibus (118) < 4 A7 54 FF 
> Ibus (118) > 6 A7 0 0 52 FF 
> Ibus (118) < 4 A8 53 FF 
> Ibus (118) > 6 A8 0 0 51 FF 
> Ibus (118) < 4 A9 52 FF 
> Ibus (118) > 6 A9 0 0 50 FF 
> Ibus (116) < 4 A1 5A FF 
> Ibus (116) > 6 A1 0 0 58 FF 
> Ibus (116) < 4 A2 59 FF 
> Ibus (116) > 6 A2 0 0 57 FF 
> Ibus (116) < 4 A3 58 FF 
> Ibus (116) > 8 A3 0 0 0 0 54 FF 
> Ibus (116) < 4 A4 57 FF 
> Ibus (116) > 8 A4 0 0 0 0 53 FF 
> Ibus (116) < 4 A5 56 FF 
> Ibus (116) > 8 A5 0 0 0 0 52 FF 
> Ibus (116) < 4 A6 55 FF 
> Ibus (116) > 6 A6 0 0 53 FF 
> Ibus (116) < 4 A7 54 FF 
> Ibus (116) > 6 A7 0 0 52 FF 
> Ibus (116) < 4 A8 53 FF 
> Ibus (116) > 6 A8 0 0 51 FF 
> Ibus (116) < 4 A9 52 FF 
> Ibus (116) > 6 A9 0 0 50 FF 
> Ibus (116) < 4 A1 5A FF 
> Ibus (116) > 6 A1 0 0 58 FF 
> Ibus (116) < 4 A2 59 FF 
> Ibus (116) > 6 A2 0 0 57 FF 
> Ibus (116) < 4 A3 58 FF 
> Ibus (116) > 8 A3 0 0 0 0 54 FF 
> Ibus (116) < 4 A4 57 FF 
> Ibus (116) > 8 A4 0 0 0 0 53 FF 
> Ibus (116) < 4 A5 56 FF 
> Ibus (116) > 8 A5 0 0 0 0 52 FF 
> Ibus (116) < 4 A6 55 FF 
> Ibus (116) > 6 A6 0 0 53 FF 
> Ibus (116) < 4 A7 54 FF 
> 
>

**Comment by dgatf** [comment]
MSRC is not reading data from the GPS, as there is no GPS output in debug. That's why you see all zeroes in receiver from GPS.

Please check:
1. GPS is connected to GPIO 6
2. GPS baudrate should be the same as in MSRC gui (9600bps by default)
3. GPS Is connected to a  5v suply  and connected to a GND pin in MSRC

You should see something like this:
![Captura desde 2024-02-24 10-12-32](https://github.com/dgatf/msrc/assets/33811722/dd49f649-307a-4342-a9fc-bd6a6cc23052)

You can disconect the receiver to MSRC to focus on the GPS issue.
![Captura desde 2024-02-24 10-16-49](https://github.com/dgatf/msrc/assets/33811722/02426599-b74d-449c-b144-9433c07b02fd)
